trigger:
  - master
  - develop

variables:
  ${{ if eq( variables['Build.SourceBranchName'], 'master' ) }}:
    buildVersion: 'production'
    targetFolder: '/var/www/alexandrya.aquarius.irish'
  ${{ if eq( variables['Build.SourceBranchName'], 'develop' ) }}:
    buildVersion: 'test'
    targetFolder: '/var/www/alexandrya.test.aquarius.irish'

pool: Aquarius VPS Agent

steps:
  - task: npmAuthenticate@0
    inputs:
      workingFile: '.npmrc'
      customEndpoint: 'Aquarius-npm-registry'

  - script: npm install
    displayName: 'npm install'
    workingDirectory: $(Build.SourcesDirectory)

  - script: npx ng lint
    displayName: 'execute lint'
    workingDirectory: $(Build.SourcesDirectory)

  - script: npx ng test  --browsers=ChromeHeadless --watch=false
    displayName: 'execute test'
    workingDirectory: $(Build.SourcesDirectory)

  - script: npm run build -c $(buildVersion)
    displayName: 'npm build'
    workingDirectory: $(Build.SourcesDirectory)

  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'SSH Aquarius VPS'
      sourceFolder: '$(Build.SourcesDirectory)/www/'
      contents: '**'
      targetFolder: '$(targetFolder)'
      readyTimeout: '20000'
